name: entrepreneur
description: Un jeu d'aventure entrepreneurial pour apprendre l'entrepreneuriat de manière ludique.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.27.0
  flame_tiled: ^3.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.5.3
  flutter_svg: ^2.0.17
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/Players
    - assets/images/maps/
    - assets/images/ui/
    - assets/audio/
    - assets/images/
    - assets/icons/
